services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: konobangu
      POSTGRES_PASSWORD: konobangu
      POSTGRES_DB: konobangu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
