[toolchain]
channel = "nightly-2025-06-03"
# [simd not supported by cranelift](https://github.com/rust-lang/rustc_codegen_cranelift/issues/171)
# components = ["rustfmt", "clippy", "rustc-codegen-cranelift"]
components = ["rustfmt", "clippy"]
profile = "default"
