[package]
name = "dev-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.29"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
