[package]
name = "dlsignal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dlsignal"
path = "src/lib.rs"

[features]
default = []
testcontainers = []

[dependencies]
quirks_path = { path = "../quirks-path" }
async-trait = "0.1.83"
chrono = "0.4.39"
eyre = "0.6.12"
futures = "0.3.31"
itertools = "0.13.0"
lazy_static = "1.5.0"
librqbit-core = "4"
qbit-rs = { git = "https://github.com/lonelyhentxi/qbit.git", rev = "a2c70aa", features = [
  "default",
  "builder",
] }
regex = "1.11.1"
serde = "1.0.216"
thiserror = "2.0.9"
tokio = "1.42.0"
url = "2.5.4"
reqwest = "0.12.11"
bytes = "1.9.0"

[dev-dependencies]
testcontainers = { version = "0.23.1" }
testcontainers-modules = { version = "0.11.4" }
