[package]
name = "util-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
snafu = { workspace = true }
convert_case = { workspace = true }

quote = "1"
syn = "2"
darling = "0.20"
proc-macro2 = { version = "1" }
