/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as R404Import } from './routes/404'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AppTasksRouteImport } from './routes/_app/tasks/route'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions/route'
import { Route as AppSettingsRouteImport } from './routes/_app/settings/route'
import { Route as AppPlaygroundRouteImport } from './routes/_app/playground/route'
import { Route as AppCredential3rdRouteImport } from './routes/_app/credential3rd/route'
import { Route as AppBangumiRouteImport } from './routes/_app/bangumi/route'
import { Route as AuthOidcCallbackImport } from './routes/auth/oidc/callback'
import { Route as AppTasksManageImport } from './routes/_app/tasks/manage'
import { Route as AppSubscriptionsManageImport } from './routes/_app/subscriptions/manage'
import { Route as AppSubscriptionsCreateImport } from './routes/_app/subscriptions/create'
import { Route as AppSettingsDownloaderImport } from './routes/_app/settings/downloader'
import { Route as AppPlaygroundGraphqlApiImport } from './routes/_app/playground/graphql-api'
import { Route as AppCredential3rdManageImport } from './routes/_app/credential3rd/manage'
import { Route as AppCredential3rdCreateImport } from './routes/_app/credential3rd/create'
import { Route as AppBangumiManageImport } from './routes/_app/bangumi/manage'
import { Route as AppExploreExploreImport } from './routes/_app/_explore/explore'
import { Route as AppTasksDetailIdImport } from './routes/_app/tasks/detail.$id'
import { Route as AppSubscriptionsEditIdImport } from './routes/_app/subscriptions/edit.$id'
import { Route as AppSubscriptionsDetailIdImport } from './routes/_app/subscriptions/detail.$id'
import { Route as AppCredential3rdEditIdImport } from './routes/_app/credential3rd/edit.$id'
import { Route as AppCredential3rdDetailIdImport } from './routes/_app/credential3rd/detail.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AppTasksRouteRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSubscriptionsRouteRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSettingsRouteRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppPlaygroundRouteRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCredential3rdRouteRoute = AppCredential3rdRouteImport.update({
  id: '/credential3rd',
  path: '/credential3rd',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppBangumiRouteRoute = AppBangumiRouteImport.update({
  id: '/bangumi',
  path: '/bangumi',
  getParentRoute: () => AppRouteRoute,
} as any)

const AuthOidcCallbackRoute = AuthOidcCallbackImport.update({
  id: '/auth/oidc/callback',
  path: '/auth/oidc/callback',
  getParentRoute: () => rootRoute,
} as any)

const AppTasksManageRoute = AppTasksManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppTasksRouteRoute,
} as any)

const AppSubscriptionsManageRoute = AppSubscriptionsManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppSubscriptionsCreateRoute = AppSubscriptionsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppSettingsDownloaderRoute = AppSettingsDownloaderImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

const AppPlaygroundGraphqlApiRoute = AppPlaygroundGraphqlApiImport.update({
  id: '/graphql-api',
  path: '/graphql-api',
  getParentRoute: () => AppPlaygroundRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/playground/graphql-api.lazy').then((d) => d.Route),
)

const AppCredential3rdManageRoute = AppCredential3rdManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppCredential3rdRouteRoute,
} as any)

const AppCredential3rdCreateRoute = AppCredential3rdCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCredential3rdRouteRoute,
} as any)

const AppBangumiManageRoute = AppBangumiManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppBangumiRouteRoute,
} as any)

const AppExploreExploreRoute = AppExploreExploreImport.update({
  id: '/_explore/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTasksDetailIdRoute = AppTasksDetailIdImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => AppTasksRouteRoute,
} as any)

const AppSubscriptionsEditIdRoute = AppSubscriptionsEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppSubscriptionsDetailIdRoute = AppSubscriptionsDetailIdImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppCredential3rdEditIdRoute = AppCredential3rdEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppCredential3rdRouteRoute,
} as any)

const AppCredential3rdDetailIdRoute = AppCredential3rdDetailIdImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => AppCredential3rdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_app/bangumi': {
      id: '/_app/bangumi'
      path: '/bangumi'
      fullPath: '/bangumi'
      preLoaderRoute: typeof AppBangumiRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/credential3rd': {
      id: '/_app/credential3rd'
      path: '/credential3rd'
      fullPath: '/credential3rd'
      preLoaderRoute: typeof AppCredential3rdRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_app/_explore/explore': {
      id: '/_app/_explore/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreExploreImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/bangumi/manage': {
      id: '/_app/bangumi/manage'
      path: '/manage'
      fullPath: '/bangumi/manage'
      preLoaderRoute: typeof AppBangumiManageImport
      parentRoute: typeof AppBangumiRouteImport
    }
    '/_app/credential3rd/create': {
      id: '/_app/credential3rd/create'
      path: '/create'
      fullPath: '/credential3rd/create'
      preLoaderRoute: typeof AppCredential3rdCreateImport
      parentRoute: typeof AppCredential3rdRouteImport
    }
    '/_app/credential3rd/manage': {
      id: '/_app/credential3rd/manage'
      path: '/manage'
      fullPath: '/credential3rd/manage'
      preLoaderRoute: typeof AppCredential3rdManageImport
      parentRoute: typeof AppCredential3rdRouteImport
    }
    '/_app/playground/graphql-api': {
      id: '/_app/playground/graphql-api'
      path: '/graphql-api'
      fullPath: '/playground/graphql-api'
      preLoaderRoute: typeof AppPlaygroundGraphqlApiImport
      parentRoute: typeof AppPlaygroundRouteImport
    }
    '/_app/settings/downloader': {
      id: '/_app/settings/downloader'
      path: '/downloader'
      fullPath: '/settings/downloader'
      preLoaderRoute: typeof AppSettingsDownloaderImport
      parentRoute: typeof AppSettingsRouteImport
    }
    '/_app/subscriptions/create': {
      id: '/_app/subscriptions/create'
      path: '/create'
      fullPath: '/subscriptions/create'
      preLoaderRoute: typeof AppSubscriptionsCreateImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/_app/subscriptions/manage': {
      id: '/_app/subscriptions/manage'
      path: '/manage'
      fullPath: '/subscriptions/manage'
      preLoaderRoute: typeof AppSubscriptionsManageImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/_app/tasks/manage': {
      id: '/_app/tasks/manage'
      path: '/manage'
      fullPath: '/tasks/manage'
      preLoaderRoute: typeof AppTasksManageImport
      parentRoute: typeof AppTasksRouteImport
    }
    '/auth/oidc/callback': {
      id: '/auth/oidc/callback'
      path: '/auth/oidc/callback'
      fullPath: '/auth/oidc/callback'
      preLoaderRoute: typeof AuthOidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_app/credential3rd/detail/$id': {
      id: '/_app/credential3rd/detail/$id'
      path: '/detail/$id'
      fullPath: '/credential3rd/detail/$id'
      preLoaderRoute: typeof AppCredential3rdDetailIdImport
      parentRoute: typeof AppCredential3rdRouteImport
    }
    '/_app/credential3rd/edit/$id': {
      id: '/_app/credential3rd/edit/$id'
      path: '/edit/$id'
      fullPath: '/credential3rd/edit/$id'
      preLoaderRoute: typeof AppCredential3rdEditIdImport
      parentRoute: typeof AppCredential3rdRouteImport
    }
    '/_app/subscriptions/detail/$id': {
      id: '/_app/subscriptions/detail/$id'
      path: '/detail/$id'
      fullPath: '/subscriptions/detail/$id'
      preLoaderRoute: typeof AppSubscriptionsDetailIdImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/_app/subscriptions/edit/$id': {
      id: '/_app/subscriptions/edit/$id'
      path: '/edit/$id'
      fullPath: '/subscriptions/edit/$id'
      preLoaderRoute: typeof AppSubscriptionsEditIdImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/_app/tasks/detail/$id': {
      id: '/_app/tasks/detail/$id'
      path: '/detail/$id'
      fullPath: '/tasks/detail/$id'
      preLoaderRoute: typeof AppTasksDetailIdImport
      parentRoute: typeof AppTasksRouteImport
    }
  }
}

// Create and export the route tree

interface AppBangumiRouteRouteChildren {
  AppBangumiManageRoute: typeof AppBangumiManageRoute
}

const AppBangumiRouteRouteChildren: AppBangumiRouteRouteChildren = {
  AppBangumiManageRoute: AppBangumiManageRoute,
}

const AppBangumiRouteRouteWithChildren = AppBangumiRouteRoute._addFileChildren(
  AppBangumiRouteRouteChildren,
)

interface AppCredential3rdRouteRouteChildren {
  AppCredential3rdCreateRoute: typeof AppCredential3rdCreateRoute
  AppCredential3rdManageRoute: typeof AppCredential3rdManageRoute
  AppCredential3rdDetailIdRoute: typeof AppCredential3rdDetailIdRoute
  AppCredential3rdEditIdRoute: typeof AppCredential3rdEditIdRoute
}

const AppCredential3rdRouteRouteChildren: AppCredential3rdRouteRouteChildren = {
  AppCredential3rdCreateRoute: AppCredential3rdCreateRoute,
  AppCredential3rdManageRoute: AppCredential3rdManageRoute,
  AppCredential3rdDetailIdRoute: AppCredential3rdDetailIdRoute,
  AppCredential3rdEditIdRoute: AppCredential3rdEditIdRoute,
}

const AppCredential3rdRouteRouteWithChildren =
  AppCredential3rdRouteRoute._addFileChildren(
    AppCredential3rdRouteRouteChildren,
  )

interface AppPlaygroundRouteRouteChildren {
  AppPlaygroundGraphqlApiRoute: typeof AppPlaygroundGraphqlApiRoute
}

const AppPlaygroundRouteRouteChildren: AppPlaygroundRouteRouteChildren = {
  AppPlaygroundGraphqlApiRoute: AppPlaygroundGraphqlApiRoute,
}

const AppPlaygroundRouteRouteWithChildren =
  AppPlaygroundRouteRoute._addFileChildren(AppPlaygroundRouteRouteChildren)

interface AppSettingsRouteRouteChildren {
  AppSettingsDownloaderRoute: typeof AppSettingsDownloaderRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsDownloaderRoute: AppSettingsDownloaderRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppSubscriptionsRouteRouteChildren {
  AppSubscriptionsCreateRoute: typeof AppSubscriptionsCreateRoute
  AppSubscriptionsManageRoute: typeof AppSubscriptionsManageRoute
  AppSubscriptionsDetailIdRoute: typeof AppSubscriptionsDetailIdRoute
  AppSubscriptionsEditIdRoute: typeof AppSubscriptionsEditIdRoute
}

const AppSubscriptionsRouteRouteChildren: AppSubscriptionsRouteRouteChildren = {
  AppSubscriptionsCreateRoute: AppSubscriptionsCreateRoute,
  AppSubscriptionsManageRoute: AppSubscriptionsManageRoute,
  AppSubscriptionsDetailIdRoute: AppSubscriptionsDetailIdRoute,
  AppSubscriptionsEditIdRoute: AppSubscriptionsEditIdRoute,
}

const AppSubscriptionsRouteRouteWithChildren =
  AppSubscriptionsRouteRoute._addFileChildren(
    AppSubscriptionsRouteRouteChildren,
  )

interface AppTasksRouteRouteChildren {
  AppTasksManageRoute: typeof AppTasksManageRoute
  AppTasksDetailIdRoute: typeof AppTasksDetailIdRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksManageRoute: AppTasksManageRoute,
  AppTasksDetailIdRoute: AppTasksDetailIdRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppBangumiRouteRoute: typeof AppBangumiRouteRouteWithChildren
  AppCredential3rdRouteRoute: typeof AppCredential3rdRouteRouteWithChildren
  AppPlaygroundRouteRoute: typeof AppPlaygroundRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppSubscriptionsRouteRoute: typeof AppSubscriptionsRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppExploreExploreRoute: typeof AppExploreExploreRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBangumiRouteRoute: AppBangumiRouteRouteWithChildren,
  AppCredential3rdRouteRoute: AppCredential3rdRouteRouteWithChildren,
  AppPlaygroundRouteRoute: AppPlaygroundRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppSubscriptionsRouteRoute: AppSubscriptionsRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppExploreExploreRoute: AppExploreExploreRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/bangumi': typeof AppBangumiRouteRouteWithChildren
  '/credential3rd': typeof AppCredential3rdRouteRouteWithChildren
  '/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/explore': typeof AppExploreExploreRoute
  '/bangumi/manage': typeof AppBangumiManageRoute
  '/credential3rd/create': typeof AppCredential3rdCreateRoute
  '/credential3rd/manage': typeof AppCredential3rdManageRoute
  '/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/settings/downloader': typeof AppSettingsDownloaderRoute
  '/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/tasks/manage': typeof AppTasksManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/credential3rd/detail/$id': typeof AppCredential3rdDetailIdRoute
  '/credential3rd/edit/$id': typeof AppCredential3rdEditIdRoute
  '/subscriptions/detail/$id': typeof AppSubscriptionsDetailIdRoute
  '/subscriptions/edit/$id': typeof AppSubscriptionsEditIdRoute
  '/tasks/detail/$id': typeof AppTasksDetailIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/bangumi': typeof AppBangumiRouteRouteWithChildren
  '/credential3rd': typeof AppCredential3rdRouteRouteWithChildren
  '/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/explore': typeof AppExploreExploreRoute
  '/bangumi/manage': typeof AppBangumiManageRoute
  '/credential3rd/create': typeof AppCredential3rdCreateRoute
  '/credential3rd/manage': typeof AppCredential3rdManageRoute
  '/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/settings/downloader': typeof AppSettingsDownloaderRoute
  '/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/tasks/manage': typeof AppTasksManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/credential3rd/detail/$id': typeof AppCredential3rdDetailIdRoute
  '/credential3rd/edit/$id': typeof AppCredential3rdEditIdRoute
  '/subscriptions/detail/$id': typeof AppSubscriptionsDetailIdRoute
  '/subscriptions/edit/$id': typeof AppSubscriptionsEditIdRoute
  '/tasks/detail/$id': typeof AppTasksDetailIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/_app/bangumi': typeof AppBangumiRouteRouteWithChildren
  '/_app/credential3rd': typeof AppCredential3rdRouteRouteWithChildren
  '/_app/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/_explore/explore': typeof AppExploreExploreRoute
  '/_app/bangumi/manage': typeof AppBangumiManageRoute
  '/_app/credential3rd/create': typeof AppCredential3rdCreateRoute
  '/_app/credential3rd/manage': typeof AppCredential3rdManageRoute
  '/_app/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/_app/settings/downloader': typeof AppSettingsDownloaderRoute
  '/_app/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/_app/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/_app/tasks/manage': typeof AppTasksManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/_app/credential3rd/detail/$id': typeof AppCredential3rdDetailIdRoute
  '/_app/credential3rd/edit/$id': typeof AppCredential3rdEditIdRoute
  '/_app/subscriptions/detail/$id': typeof AppSubscriptionsDetailIdRoute
  '/_app/subscriptions/edit/$id': typeof AppSubscriptionsEditIdRoute
  '/_app/tasks/detail/$id': typeof AppTasksDetailIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/404'
    | '/about'
    | '/bangumi'
    | '/credential3rd'
    | '/playground'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/explore'
    | '/bangumi/manage'
    | '/credential3rd/create'
    | '/credential3rd/manage'
    | '/playground/graphql-api'
    | '/settings/downloader'
    | '/subscriptions/create'
    | '/subscriptions/manage'
    | '/tasks/manage'
    | '/auth/oidc/callback'
    | '/credential3rd/detail/$id'
    | '/credential3rd/edit/$id'
    | '/subscriptions/detail/$id'
    | '/subscriptions/edit/$id'
    | '/tasks/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/404'
    | '/about'
    | '/bangumi'
    | '/credential3rd'
    | '/playground'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/explore'
    | '/bangumi/manage'
    | '/credential3rd/create'
    | '/credential3rd/manage'
    | '/playground/graphql-api'
    | '/settings/downloader'
    | '/subscriptions/create'
    | '/subscriptions/manage'
    | '/tasks/manage'
    | '/auth/oidc/callback'
    | '/credential3rd/detail/$id'
    | '/credential3rd/edit/$id'
    | '/subscriptions/detail/$id'
    | '/subscriptions/edit/$id'
    | '/tasks/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/404'
    | '/about'
    | '/_app/bangumi'
    | '/_app/credential3rd'
    | '/_app/playground'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/_explore/explore'
    | '/_app/bangumi/manage'
    | '/_app/credential3rd/create'
    | '/_app/credential3rd/manage'
    | '/_app/playground/graphql-api'
    | '/_app/settings/downloader'
    | '/_app/subscriptions/create'
    | '/_app/subscriptions/manage'
    | '/_app/tasks/manage'
    | '/auth/oidc/callback'
    | '/_app/credential3rd/detail/$id'
    | '/_app/credential3rd/edit/$id'
    | '/_app/subscriptions/detail/$id'
    | '/_app/subscriptions/edit/$id'
    | '/_app/tasks/detail/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthOidcCallbackRoute: typeof AuthOidcCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthOidcCallbackRoute: AuthOidcCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/404",
        "/about",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/oidc/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/bangumi",
        "/_app/credential3rd",
        "/_app/playground",
        "/_app/settings",
        "/_app/subscriptions",
        "/_app/tasks",
        "/_app/_explore/explore"
      ]
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_app/bangumi": {
      "filePath": "_app/bangumi/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/bangumi/manage"
      ]
    },
    "/_app/credential3rd": {
      "filePath": "_app/credential3rd/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/credential3rd/create",
        "/_app/credential3rd/manage",
        "/_app/credential3rd/detail/$id",
        "/_app/credential3rd/edit/$id"
      ]
    },
    "/_app/playground": {
      "filePath": "_app/playground/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/playground/graphql-api"
      ]
    },
    "/_app/settings": {
      "filePath": "_app/settings/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/settings/downloader"
      ]
    },
    "/_app/subscriptions": {
      "filePath": "_app/subscriptions/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/subscriptions/create",
        "/_app/subscriptions/manage",
        "/_app/subscriptions/detail/$id",
        "/_app/subscriptions/edit/$id"
      ]
    },
    "/_app/tasks": {
      "filePath": "_app/tasks/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/tasks/manage",
        "/_app/tasks/detail/$id"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/_app/_explore/explore": {
      "filePath": "_app/_explore/explore.tsx",
      "parent": "/_app"
    },
    "/_app/bangumi/manage": {
      "filePath": "_app/bangumi/manage.tsx",
      "parent": "/_app/bangumi"
    },
    "/_app/credential3rd/create": {
      "filePath": "_app/credential3rd/create.tsx",
      "parent": "/_app/credential3rd"
    },
    "/_app/credential3rd/manage": {
      "filePath": "_app/credential3rd/manage.tsx",
      "parent": "/_app/credential3rd"
    },
    "/_app/playground/graphql-api": {
      "filePath": "_app/playground/graphql-api.tsx",
      "parent": "/_app/playground"
    },
    "/_app/settings/downloader": {
      "filePath": "_app/settings/downloader.tsx",
      "parent": "/_app/settings"
    },
    "/_app/subscriptions/create": {
      "filePath": "_app/subscriptions/create.tsx",
      "parent": "/_app/subscriptions"
    },
    "/_app/subscriptions/manage": {
      "filePath": "_app/subscriptions/manage.tsx",
      "parent": "/_app/subscriptions"
    },
    "/_app/tasks/manage": {
      "filePath": "_app/tasks/manage.tsx",
      "parent": "/_app/tasks"
    },
    "/auth/oidc/callback": {
      "filePath": "auth/oidc/callback.tsx"
    },
    "/_app/credential3rd/detail/$id": {
      "filePath": "_app/credential3rd/detail.$id.tsx",
      "parent": "/_app/credential3rd"
    },
    "/_app/credential3rd/edit/$id": {
      "filePath": "_app/credential3rd/edit.$id.tsx",
      "parent": "/_app/credential3rd"
    },
    "/_app/subscriptions/detail/$id": {
      "filePath": "_app/subscriptions/detail.$id.tsx",
      "parent": "/_app/subscriptions"
    },
    "/_app/subscriptions/edit/$id": {
      "filePath": "_app/subscriptions/edit.$id.tsx",
      "parent": "/_app/subscriptions"
    },
    "/_app/tasks/detail/$id": {
      "filePath": "_app/tasks/detail.$id.tsx",
      "parent": "/_app/tasks"
    }
  }
}
ROUTE_MANIFEST_END */
