[alias]
recorder-playground = "run -p recorder  --example playground -- --environment development"

[build]
rustflags = ["-Zthreads=8", "--cfg", "feature=\"testcontainers\""]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Zthreads=8", "-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zthreads=8", "-Zshare-generics=n"]

# NOTE: you must install [Mach-O LLD Port](https://lld.llvm.org/MachO/index.html) on mac. you can easily do this by installing llvm which includes lld with the "brew" package manager:
# `brew install llvm`
#[target.x86_64-apple-darwin]
#rustflags = [
#    "-Zthreads=8",
#    "-C",
#    "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
#    "-Zshare-generics=y",
#]

# NOTE: you must install [Mach-O LLD Port](https://lld.llvm.org/MachO/index.html) on mac. you can easily do this by installing llvm which includes lld with the "brew" package manager:
# `brew install llvm`
#[target.aarch64-apple-darwin]
#rustflags = [
#    "-Zthreads=8",
#    "-C",
#    "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
#    "-Zshare-generics=y",
#]
