[alias]
recorder-playground = "run -p recorder  --example playground -- --environment development"

[build]
rustflags = [
    "-Zthreads=8",
    "--cfg",
    "feature=\"testcontainers\"",
    "-Zshare-generics=y",
]
