//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::{
    bangumi::Entity as Bangumi, episodes::Entity as Episodes, subscribers::Entity as Subscribers,
    subscriptions::Entity as Subscriptions,
};
