[package]
name = "testing-torrents"
version = "0.1.0"
edition = "2024"

[dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
testcontainers-ext = { workspace = true }
serde = { workspace = true }
