/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AppImport } from './routes/_app'
import { Route as R404Import } from './routes/404'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AppExploreImport } from './routes/_app/explore'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions/route'
import { Route as AppSettingsRouteImport } from './routes/_app/settings/route'
import { Route as AppPlaygroundRouteImport } from './routes/_app/playground/route'
import { Route as AuthOidcCallbackImport } from './routes/auth/oidc/callback'
import { Route as AppSubscriptionsManageImport } from './routes/_app/subscriptions/manage'
import { Route as AppSubscriptionsCreateImport } from './routes/_app/subscriptions/create'
import { Route as AppPlaygroundGraphqlApiImport } from './routes/_app/playground/graphql-api'
import { Route as AppSubscriptionsEditSubscriptionIdImport } from './routes/_app/subscriptions/edit.$subscription-id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AppExploreRoute = AppExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)

const AppSubscriptionsRouteRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsRouteRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppPlaygroundRouteRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)

const AuthOidcCallbackRoute = AuthOidcCallbackImport.update({
  id: '/auth/oidc/callback',
  path: '/auth/oidc/callback',
  getParentRoute: () => rootRoute,
} as any)

const AppSubscriptionsManageRoute = AppSubscriptionsManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppSubscriptionsCreateRoute = AppSubscriptionsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppSubscriptionsRouteRoute,
} as any)

const AppPlaygroundGraphqlApiRoute = AppPlaygroundGraphqlApiImport.update({
  id: '/graphql-api',
  path: '/graphql-api',
  getParentRoute: () => AppPlaygroundRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/playground/graphql-api.lazy').then((d) => d.Route),
)

const AppSubscriptionsEditSubscriptionIdRoute =
  AppSubscriptionsEditSubscriptionIdImport.update({
    id: '/edit/$subscription-id',
    path: '/edit/$subscription-id',
    getParentRoute: () => AppSubscriptionsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreImport
      parentRoute: typeof AppImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_app/playground/graphql-api': {
      id: '/_app/playground/graphql-api'
      path: '/graphql-api'
      fullPath: '/playground/graphql-api'
      preLoaderRoute: typeof AppPlaygroundGraphqlApiImport
      parentRoute: typeof AppPlaygroundRouteImport
    }
    '/_app/subscriptions/create': {
      id: '/_app/subscriptions/create'
      path: '/create'
      fullPath: '/subscriptions/create'
      preLoaderRoute: typeof AppSubscriptionsCreateImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/_app/subscriptions/manage': {
      id: '/_app/subscriptions/manage'
      path: '/manage'
      fullPath: '/subscriptions/manage'
      preLoaderRoute: typeof AppSubscriptionsManageImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
    '/auth/oidc/callback': {
      id: '/auth/oidc/callback'
      path: '/auth/oidc/callback'
      fullPath: '/auth/oidc/callback'
      preLoaderRoute: typeof AuthOidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_app/subscriptions/edit/$subscription-id': {
      id: '/_app/subscriptions/edit/$subscription-id'
      path: '/edit/$subscription-id'
      fullPath: '/subscriptions/edit/$subscription-id'
      preLoaderRoute: typeof AppSubscriptionsEditSubscriptionIdImport
      parentRoute: typeof AppSubscriptionsRouteImport
    }
  }
}

// Create and export the route tree

interface AppPlaygroundRouteRouteChildren {
  AppPlaygroundGraphqlApiRoute: typeof AppPlaygroundGraphqlApiRoute
}

const AppPlaygroundRouteRouteChildren: AppPlaygroundRouteRouteChildren = {
  AppPlaygroundGraphqlApiRoute: AppPlaygroundGraphqlApiRoute,
}

const AppPlaygroundRouteRouteWithChildren =
  AppPlaygroundRouteRoute._addFileChildren(AppPlaygroundRouteRouteChildren)

interface AppSubscriptionsRouteRouteChildren {
  AppSubscriptionsCreateRoute: typeof AppSubscriptionsCreateRoute
  AppSubscriptionsManageRoute: typeof AppSubscriptionsManageRoute
  AppSubscriptionsEditSubscriptionIdRoute: typeof AppSubscriptionsEditSubscriptionIdRoute
}

const AppSubscriptionsRouteRouteChildren: AppSubscriptionsRouteRouteChildren = {
  AppSubscriptionsCreateRoute: AppSubscriptionsCreateRoute,
  AppSubscriptionsManageRoute: AppSubscriptionsManageRoute,
  AppSubscriptionsEditSubscriptionIdRoute:
    AppSubscriptionsEditSubscriptionIdRoute,
}

const AppSubscriptionsRouteRouteWithChildren =
  AppSubscriptionsRouteRoute._addFileChildren(
    AppSubscriptionsRouteRouteChildren,
  )

interface AppRouteChildren {
  AppPlaygroundRouteRoute: typeof AppPlaygroundRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppSubscriptionsRouteRoute: typeof AppSubscriptionsRouteRouteWithChildren
  AppExploreRoute: typeof AppExploreRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPlaygroundRouteRoute: AppPlaygroundRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppSubscriptionsRouteRoute: AppSubscriptionsRouteRouteWithChildren,
  AppExploreRoute: AppExploreRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRoute
  '/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/explore': typeof AppExploreRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/subscriptions/edit/$subscription-id': typeof AppSubscriptionsEditSubscriptionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRoute
  '/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/explore': typeof AppExploreRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/subscriptions/edit/$subscription-id': typeof AppSubscriptionsEditSubscriptionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/playground': typeof AppPlaygroundRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_app/subscriptions': typeof AppSubscriptionsRouteRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/playground/graphql-api': typeof AppPlaygroundGraphqlApiRoute
  '/_app/subscriptions/create': typeof AppSubscriptionsCreateRoute
  '/_app/subscriptions/manage': typeof AppSubscriptionsManageRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/_app/subscriptions/edit/$subscription-id': typeof AppSubscriptionsEditSubscriptionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | ''
    | '/about'
    | '/playground'
    | '/settings'
    | '/subscriptions'
    | '/explore'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/playground/graphql-api'
    | '/subscriptions/create'
    | '/subscriptions/manage'
    | '/auth/oidc/callback'
    | '/subscriptions/edit/$subscription-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | ''
    | '/about'
    | '/playground'
    | '/settings'
    | '/subscriptions'
    | '/explore'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/playground/graphql-api'
    | '/subscriptions/create'
    | '/subscriptions/manage'
    | '/auth/oidc/callback'
    | '/subscriptions/edit/$subscription-id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/about'
    | '/_app/playground'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/explore'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/playground/graphql-api'
    | '/_app/subscriptions/create'
    | '/_app/subscriptions/manage'
    | '/auth/oidc/callback'
    | '/_app/subscriptions/edit/$subscription-id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthOidcCallbackRoute: typeof AuthOidcCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthOidcCallbackRoute: AuthOidcCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/404",
        "/_app",
        "/about",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/oidc/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/playground",
        "/_app/settings",
        "/_app/subscriptions",
        "/_app/explore"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_app/playground": {
      "filePath": "_app/playground/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/playground/graphql-api"
      ]
    },
    "/_app/settings": {
      "filePath": "_app/settings/route.tsx",
      "parent": "/_app"
    },
    "/_app/subscriptions": {
      "filePath": "_app/subscriptions/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/subscriptions/create",
        "/_app/subscriptions/manage",
        "/_app/subscriptions/edit/$subscription-id"
      ]
    },
    "/_app/explore": {
      "filePath": "_app/explore.tsx",
      "parent": "/_app"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/_app/playground/graphql-api": {
      "filePath": "_app/playground/graphql-api.tsx",
      "parent": "/_app/playground"
    },
    "/_app/subscriptions/create": {
      "filePath": "_app/subscriptions/create.tsx",
      "parent": "/_app/subscriptions"
    },
    "/_app/subscriptions/manage": {
      "filePath": "_app/subscriptions/manage.tsx",
      "parent": "/_app/subscriptions"
    },
    "/auth/oidc/callback": {
      "filePath": "auth/oidc/callback.tsx"
    },
    "/_app/subscriptions/edit/$subscription-id": {
      "filePath": "_app/subscriptions/edit.$subscription-id.tsx",
      "parent": "/_app/subscriptions"
    }
  }
}
ROUTE_MANIFEST_END */
