[package]
name = "quirks_path"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
percent-encoding = "2.3.1"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.57"
tracing = "0.1.41"
url = "2.5.0"

[dev-dependencies]
tracing = "0.1.41"
